#!/bin/bash

# package.jsonファイルのパスを指定
PACKAGE_JSON="package.json"

# sedコマンドを使用してバージョンを更新
sed -i '' -e 's/"next": ".*"/"next": "14.2.5"/' \
    -e 's/"react": ".*"/"react": "18.3.1"/' \
    -e 's/"react-dom": ".*"/"react-dom": "18.3.1"/' \
    "$PACKAGE_JSON"

echo "package.jsonファイルが更新されました。"

rm -rf node_modules
bun i
