import {
	ArrowLeft,
	ChevronLeft,
	ChevronRight,
	ChevronsRight,
	Clock,
	File,
	FileText,
	Globe,
	History,
	LayoutGrid,
	Lightbulb,
	MessageSquare,
	Minus,
	MoreHorizontal,
	Pen,
	Plus,
	RefreshCw,
	Sparkles,
} from "lucide-react";

const Logo = () => (
	<svg
		width="24"
		height="24"
		viewBox="0 0 24 24"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		<path
			d="M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z"
			fill="#E0E0E0"
		/>
		<path d="M10.5 7.5H8V16.5H10.5V7.5Z" fill="#0D0D0F" />
		<path
			d="M16 15.5C16 16.3284 15.3284 17 14.5 17C13.6716 17 13 16.3284 13 15.5C13 14.6716 13.6716 14 14.5 14C15.3284 14 16 14.6716 16 15.5Z"
			fill="#0D0D0F"
		/>
	</svg>
);

const AgentWorkspace = () => {
	const files = [
		{
			icon: <Globe size={16} />,
			name: "chronobeach_first_pla",
			count: 4,
			active: true,
		},
		{ icon: <FileText size={16} />, name: "cyberpunk_roguelike_sy", count: 1 },
		{ icon: <FileText size={16} />, name: "futuristic_sword_slash", count: 1 },
		{ icon: <FileText size={16} />, name: "player_damage_sound_ef", count: 1 },
		{ icon: <FileText size={16} />, name: "drone_destruction_soun", count: 1 },
		{ icon: <FileText size={16} />, name: "digital_dash_blink_sou", count: 1 },
	];

	const versions = [
		"Jul 17, 10:39 AM",
		"Jul 17, 10:43 AM",
		"Jul 17, 10:48 AM",
		"Jul 17, 10:54 AM",
	];

	return (
		<div className="bg-background text-foreground min-h-screen flex flex-col font-sans">
			<div className="flex-grow flex">
				{/* Left Sidebar */}
				<aside className="w-[300px] bg-sidebar flex flex-col p-2 border-r border-border space-y-4">
					<div className="flex items-center justify-between p-2">
						<button className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
							<ArrowLeft size={16} />
							Back
						</button>
						<Logo />
					</div>

					<div className="bg-card p-3 rounded-lg space-y-3">
						<div className="flex items-start gap-3">
							<div className="bg-blue-500/20 text-blue-400 p-2 rounded-lg">
								<LayoutGrid size={20} />
							</div>
							<div>
								<h2 className="font-semibold">Agent Workspace</h2>
								<div className="flex items-center gap-1.5 text-sm">
									<span className="w-2 h-2 rounded-full bg-accent"></span>
									<span className="text-accent">Active</span>
									<span className="text-muted-foreground">· Workspace</span>
								</div>
							</div>
						</div>
						<div className="flex bg-secondary rounded-md p-1 text-sm">
							<button className="flex-1 text-muted-foreground py-1 px-2 rounded">
								Workflow
							</button>
							<button className="flex-1 bg-card text-foreground py-1 px-2 rounded-md shadow-sm">
								Files
							</button>
						</div>
					</div>

					<div className="flex-grow space-y-2 overflow-y-auto">
						<div className="flex justify-between items-center px-2 py-1">
							<h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
								Files generated by the Agent
							</h3>
							<div className="flex items-center gap-2">
								<File size={14} className="text-muted-foreground" />
								<span className="text-xs font-semibold bg-secondary px-2 py-0.5 rounded-md">
									19
								</span>
							</div>
						</div>

						{files.map((file, index) => (
							<div
								key={index}
								className={`rounded-lg ${file.active ? "bg-card" : ""}`}
							>
								<div
									className={`flex items-center justify-between p-2 rounded-lg cursor-pointer hover:bg-card/80`}
								>
									<div className="flex items-center gap-2">
										<div className="text-muted-foreground">{file.icon}</div>
										<span className="text-sm">{file.name}</span>
									</div>
									<div className="flex items-center gap-2">
										<span className="text-xs bg-secondary px-2 py-0.5 rounded-md">
											{file.count}
										</span>
										{file.active ? (
											<button className="bg-primary/20 text-primary p-1 rounded-full">
												<ChevronLeft size={16} />
											</button>
										) : (
											<ChevronRight
												size={16}
												className="text-muted-foreground"
											/>
										)}
									</div>
								</div>
								{file.active && (
									<div className="pl-4 pr-2 pb-2">
										<div className="flex justify-between items-center mb-2">
											<div className="flex items-center gap-2 text-xs text-muted-foreground">
												<History size={14} />
												<span>Versions</span>
											</div>
											<button className="text-xs text-muted-foreground hover:text-foreground">
												Select to preview
											</button>
										</div>
										<div className="space-y-2 pl-6 border-l border-dashed border-border ml-2">
											{versions.map((version, vIndex) => (
												<div
													key={vIndex}
													className="flex items-center gap-2 text-sm text-muted-foreground relative"
												>
													<div className="absolute -left-[13px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-full bg-border"></div>
													<Clock size={14} />
													<span>{version}</span>
												</div>
											))}
										</div>
									</div>
								)}
							</div>
						))}
					</div>

					<div className="bg-primary/10 text-center text-sm p-2 rounded-lg">
						Flowith Now Open to ALL.
					</div>

					<div className="flex items-center justify-between p-2 border-t border-border">
						<div className="flex items-center gap-3">
							<img
								src="/placeholder.svg?width=40&height=40"
								alt="User Avatar"
								className="w-10 h-10 rounded-full"
							/>
							<div>
								<p className="font-semibold">toyamarinyon</p>
								<p className="text-xs text-muted-foreground">
									Subscription & Settings
								</p>
							</div>
						</div>
						<button className="bg-accent/20 text-accent text-xs font-bold py-1 px-3 rounded-full border border-accent">
							TRIAL
						</button>
					</div>
				</aside>

				{/* Main Content */}
				<main className="flex-1 flex flex-col">
					<header className="flex items-center justify-between p-3 border-b border-border">
						<div className="flex items-center gap-2">
							<button className="p-2 rounded-md hover:bg-secondary">
								<MessageSquare size={18} className="text-muted-foreground" />
							</button>
							<button className="p-2 rounded-md hover:bg-secondary">
								<Plus size={18} className="text-muted-foreground" />
							</button>
							<button className="p-2 rounded-md hover:bg-secondary">
								<ChevronsRight size={18} className="text-muted-foreground" />
							</button>
							<div className="w-px h-6 bg-border mx-2"></div>
							<button className="bg-primary text-primary-foreground text-sm font-semibold px-4 py-1.5 rounded-md shadow-md shadow-primary/20">
								Share
							</button>
							<button className="p-2 rounded-md hover:bg-secondary">
								<ChevronLeft size={18} className="text-muted-foreground" />
							</button>
						</div>
						<div className="flex items-center gap-2">
							<MoreHorizontal size={20} className="text-muted-foreground" />
						</div>
					</header>

					<div className="flex-1 flex flex-col items-center justify-center p-8 overflow-y-auto space-y-4">
						<div className="w-full max-w-2xl mx-auto flex flex-col items-center">
							<div className="w-px h-16 bg-border border-l border-dashed border-border"></div>
							<div className="flex items-center gap-2 bg-card p-2 rounded-full border border-border text-sm">
								<span>Acknowledge the user's feedback and update the...</span>
								<RefreshCw size={14} className="text-muted-foreground" />
							</div>
							<div className="w-px h-8 bg-border border-l border-dashed border-border"></div>

							<div className="bg-card border border-border rounded-2xl p-6 w-full space-y-4 shadow-lg">
								<h3 className="font-semibold">Agent Neo:</h3>
								<blockquote className="border-l-2 border-primary pl-4 italic text-primary-light">
									"This document has been updated to reflect the new
									protagonist, Aya, as per user feedback."
								</blockquote>
								<div className="border-t border-border"></div>
								<div className="space-y-2">
									<h4 className="text-lg font-bold">
										Game Design Document: Chrono//Breach
									</h4>
									<h5 className="text-md font-semibold">
										1. Executive Summary
									</h5>
									<p className="text-muted-foreground text-sm">
										<span className="text-primary-light">Chrono//Breach</span>{" "}
										is a 2D action roguelike set in a collapsing digital
										reality. Players take on the role of Aya, a brilliant
										high-school student and coder...
									</p>
								</div>
								<div className="flex justify-between items-center text-xs text-muted-foreground">
									<div className="flex items-center gap-2 bg-secondary px-2 py-1 rounded-full">
										<Sparkles size={14} />
										<span>gen document</span>
									</div>
									<span>Yesterday 10:22</span>
								</div>
							</div>

							<div className="w-px h-8 bg-border border-l border-dashed border-border"></div>
							<div className="flex items-center gap-2 bg-card p-2 rounded-full border border-border text-sm">
								<span>Based on the updated Game Design Document,...</span>
								<RefreshCw size={14} className="text-muted-foreground" />
							</div>
							<div className="flex items-center gap-2 bg-secondary px-2 py-1 rounded-full text-xs mt-2">
								<Sparkles size={14} />
								<span>Agent Mode</span>
							</div>
							<div className="w-full border-t border-dashed border-border mt-4"></div>
							<div className="self-end flex items-center gap-2 bg-secondary px-2 py-1 rounded-full text-xs mt-2">
								<span>markdown</span>
								<Pen size={14} />
							</div>
						</div>
					</div>

					<footer className="p-4 border-t border-border">
						<div className="flex items-center gap-4 max-w-4xl mx-auto">
							<div className="flex items-center gap-2">
								<button className="p-2 rounded-md hover:bg-secondary">
									<Plus size={18} />
								</button>
								<button className="p-2 rounded-md hover:bg-secondary">
									<Minus size={18} />
								</button>
								<button className="p-2 rounded-md bg-primary/20 text-primary">
									<Lightbulb size={18} />
								</button>
							</div>
							<div className="flex-grow relative">
								<input
									type="text"
									placeholder="Ask Agent Neo for your task and requirements"
									className="w-full bg-card border border-border rounded-lg py-3 pl-4 pr-12 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary"
								/>
								<button className="absolute right-2 top-1/2 -translate-y-1/2 bg-foreground text-background p-1.5 rounded-md">
									<Plus size={20} />
								</button>
							</div>
						</div>
					</footer>
				</main>
			</div>
		</div>
	);
};

export default AgentWorkspace;
