export const DOCUMENT_VECTOR_STORE_MAX_FILE_SIZE_MB = 4.5;
export const DOCUMENT_VECTOR_STORE_MAX_FILE_SIZE_BYTES = Math.floor(
	DOCUMENT_VECTOR_STORE_MAX_FILE_SIZE_MB * 1024 * 1024,
);
export const DOCUMENT_VECTOR_STORE_MAX_FILE_SIZE_LABEL = `${DOCUMENT_VECTOR_STORE_MAX_FILE_SIZE_MB}MB`;
